<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="DXFLibrary">
      <HintPath>..\ThirdParty\DXF\net6.0\DXFLibrary.dll</HintPath>
    </Reference>
    <Reference Include="ShapeLibrary">
      <HintPath>..\ThirdParty\shape\net6.0\ShapeLibrary.dll</HintPath>
    </Reference>
    <Reference Include="TracerLibrary">
      <HintPath>..\ThirdParty\tracer\net6.0\TracerLibrary.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>